# Generated by Django 6.0 on 2026-08-01 07:31

import app.lib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, validators=[app.lib.validators.ContainsCharacterValidator('#', message='説明には関連するIssue番号(例: #123)を含めてください。')], verbose_name='説明'),
        ),
    ]
