# Generated by Django 6.0 on 2026-08-02 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='社員番号')),
            ],
            options={
                'ordering': ['employee_number'],
                'verbose_name': '社員',
                'verbose_name_plural': '社員',
            },
        ),
    ]
