# Generated by Django 6.0 on 2026-08-02 01:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='管理グループ名')),
                ('members', models.ManyToManyField(blank=True, related_name='management_groups', to=settings.AUTH_USER_MODEL, verbose_name='メンバー')),
            ],
            options={
                'verbose_name': '管理グループ',
                'verbose_name_plural': '管理グループ',
                'ordering': ['name'],
            },
        ),
    ]
