# Generated by Django 6.0 on 2026-08-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_managementgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='会社名')),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
                'ordering': ['name'],
            },
        ),
    ]
