# Generated by Django 6.0 on 2026-08-02 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部門名')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': '部門',
                'verbose_name_plural': '部門',
                'ordering': ['company', 'name'],
            },
        ),
    ]
