# Generated by Django 6.0 on 2026-08-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主務')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_departments', to='app.department', verbose_name='部門')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_departments', to='app.employee', verbose_name='社員')),
            ],
            options={
                'verbose_name': '社員所属部門',
                'verbose_name_plural': '社員所属部門',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='employees', through='app.EmployeeDepartment', to='app.department', verbose_name='所属部門'),
        ),
    ]
