# Generated by Django 6.0 on 2026-08-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_employeedepartment_employee_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy', to='app.department', verbose_name='部門')),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_hierarchies', to='app.department', verbose_name='親部門')),
            ],
            options={
                'verbose_name': '部門階層',
                'verbose_name_plural': '部門階層',
            },
        ),
    ]
