# Generated by Django 6.0 on 2026-08-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_employeedepartment_employee_departments_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='employeedepartment',
            table='employee_department',
        ),
        migrations.AlterModelTable(
            name='managementgroup',
            table='management_group',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
