# Generated by Django 6.0 on 2026-08-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_departmenthierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementgroup',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_groups', to='app.department', verbose_name='割当部門'),
        ),
        migrations.AddField(
            model_name='managementgroup',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='全社管理者'),
        ),
    ]
