# Generated by Django 6.0 on 2026-08-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_company_table_alter_department_table_and_more'),
        ('app', '0010_managementgroup_department_managementgroup_is_admin'),
    ]

    operations = [
    ]
