# Generated by Django 6.0 on 2026-08-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20260804_1508'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departmenthierarchy',
            table='department_hierarchy',
        ),
    ]
